export const MASTER_TEMPLATE = [
  // ── BIDDING ──────────────────────────────────────────────────────────────────────────────
  {id:'brief-received',stage:'bid',name:'Recepción de Brief',nameEN:'Brief Received',days:1,groups:[]},
  {id:'treatment-bid',stage:'bid',name:'Treatment y Presupuesto',nameEN:'Treatment & Bid',days:1,groups:[]},
  {id:'treatment-call',stage:'bid',name:'Llamada de Treatment',nameEN:'Treatment Call',days:1,groups:[]},
  {id:'award',stage:'bid',name:'Award / Adjudicación',nameEN:'Award',days:1,groups:[]},
  {id:'kickoff',stage:'bid',name:'Reunión de Inicio',nameEN:'Kickoff Meeting',days:1,groups:[]},
  // ── PRE-PRODUCCIÓN ───────────────────────────────────────────────────────────────────────
  {id:'crew-booking',stage:'pre',name:'Booking de Crew',nameEN:'Crew Booking',days:1,groups:[]},
  {id:'casting-specs',stage:'pre',name:'Especificaciones de Casting',nameEN:'Casting Specs',days:1,groups:['casting']},
  {id:'wardrobe-specs',stage:'pre',name:'Especificaciones de Vestuario',nameEN:'Wardrobe Specs',days:1,groups:['wardrobe']},
  {id:'location-specs',stage:'pre',name:'Especificaciones de Locación',nameEN:'Location Specs',days:1,groups:['locations']},
  {id:'art-specs',stage:'pre',name:'Especificaciones de Arte',nameEN:'Art Specs',days:1,groups:['art']},
  {id:'creative-call',stage:'pre',name:'Llamada Creativa',nameEN:'Creative Call',days:1,groups:[]},
  {id:'client-call',stage:'pre',name:'Llamada con Cliente',nameEN:'Client Call',days:1,groups:[]},
  {id:'casting-scout',stage:'pre',name:'Scout de Casting',nameEN:'Casting Scout',days:1,groups:['casting']},
  {id:'art-wardrobe-mb',stage:'pre',name:'Moodboards de Arte y Vestuario',nameEN:'Art & Wardrobe Moodboards',days:1,groups:[]},
  {id:'art-moodboard',stage:'pre',name:'Moodboard de Arte',nameEN:'Art Moodboard',days:1,groups:['art']},
  {id:'wardrobe-mb',stage:'pre',name:'Moodboard de Vestuario',nameEN:'Wardrobe Moodboard',days:1,groups:['wardrobe']},
  {id:'casting-1',stage:'pre',name:'Casting Día 1',nameEN:'Casting Day 1',days:1,groups:['casting']},
  {id:'casting-2',stage:'pre',name:'Casting Día 2',nameEN:'Casting Day 2',days:1,groups:['casting']},
  {id:'casting-3',stage:'pre',name:'Casting Día 3',nameEN:'Casting Day 3',days:1,groups:['casting']},
  {id:'selects-callbacks',stage:'pre',name:'Selección para Callbacks',nameEN:'Selects for Callbacks',days:1,groups:['casting']},
  {id:'callbacks-prep',stage:'pre',name:'Preparación de Callbacks',nameEN:'Callbacks Prep',days:1,groups:['casting']},
  {id:'callbacks-1',stage:'pre',name:'Callbacks Día 1',nameEN:'Callbacks Day 1',days:1,groups:['casting']},
  {id:'callbacks-2',stage:'pre',name:'Callbacks Día 2',nameEN:'Callbacks Day 2',days:1,groups:['casting']},
  {id:'talent-approval',stage:'pre',name:'Aprobación de Talento',nameEN:'Talent Approval',days:1,groups:['casting']},
  {id:'talent-booking',stage:'pre',name:'Booking de Talento',nameEN:'Talent Booking',days:1,groups:['casting']},
  {id:'talent-confirm',stage:'pre',name:'Confirmación de Talento',nameEN:'Talent Confirm',days:1,groups:['casting']},
  {id:'talent-sheet',stage:'pre',name:'Booking Sheet de Talento',nameEN:'Talent Booking Sheet',days:1,groups:['casting']},
  {id:'location-search',stage:'pre',name:'Búsqueda de Locaciones',nameEN:'Location Search',days:1,groups:['locations']},
  {id:'dir-loc-presel',stage:'pre',name:'Preselección de Locaciones del Director',nameEN:'Director\'s Location Pre-Selection',days:1,groups:['locations']},
  {id:'loc-pres-agency',stage:'pre',name:'Presentación de Locaciones a Agencia',nameEN:'Location Presentation to Agency',days:1,groups:['locations']},
  {id:'loc-agency-fb',stage:'pre',name:'Feedback de Agencia sobre Locaciones',nameEN:'Location Agency Feedback',days:1,groups:['locations']},
  {id:'loc-search-r2',stage:'pre',name:'Segunda Ronda de Búsqueda de Locaciones',nameEN:'Location Search Round 2',days:1,groups:['locations']},
  {id:'loc-pre-approval',stage:'pre',name:'Preaprobación de Locación',nameEN:'Location Pre-Approval',days:1,groups:['locations']},
  {id:'dir-scout',stage:'pre',name:'Scout del Director',nameEN:'Director\'s Scout',days:1,groups:['locations']},
  {id:'dir-loc-rec',stage:'pre',name:'Recomendación Final de Locación del Director',nameEN:'Director\'s Location Recommendation',days:1,groups:['locations']},
  {id:'loc-final-appr',stage:'pre',name:'Aprobación Final de Locación',nameEN:'Location Final Approval',days:1,groups:['locations']},
  {id:'sb-session',stage:'pre',name:'Sesión de Shooting Boards',nameEN:'Shooting Board Session',days:1,groups:['boards']},
  {id:'sb-review',stage:'pre',name:'Revisión de Shooting Boards',nameEN:'Shooting Board Review',days:1,groups:['boards']},
  {id:'wardrobe-prep',stage:'pre',name:'Preparación de Vestuario',nameEN:'Wardrobe Prep',days:1,groups:['wardrobe']},
  {id:'fitting-1',stage:'pre',name:'Fitting Día 1',nameEN:'Fitting Day 1',days:1,groups:['wardrobe']},
  {id:'fitting-2',stage:'pre',name:'Fitting Día 2',nameEN:'Fitting Day 2',days:1,groups:['wardrobe']},
  {id:'fitting-review',stage:'pre',name:'Revisión de Fitting',nameEN:'Fitting Review',days:1,groups:['wardrobe']},
  {id:'wardrobe-appr',stage:'pre',name:'Aprobación de Vestuario',nameEN:'Wardrobe Approval',days:1,groups:['wardrobe']},
  {id:'art-dept-appr',stage:'pre',name:'Aprobación de Arte',nameEN:'Art Department Approval',days:1,groups:['art']},
  {id:'ppm-prep',stage:'pre',name:'Preparación de PPM',nameEN:'Pre-Production Meeting Prep',days:1,groups:[]},
  {id:'ppm',stage:'pre',name:'Reunión de Preproducción (PPM)',nameEN:'Pre-Production Meeting (PPM)',days:1,groups:[]},
  {id:'tech-scout',stage:'pre',name:'Scout Técnico',nameEN:'Tech Scout',days:1,groups:[]},
  {id:'sched-shared',stage:'pre',name:'Shooting Schedule Compartido',nameEN:'Shooting Schedule Shared',days:1,groups:[]},
  {id:'call-sheet',stage:'pre',name:'Call Sheet Final',nameEN:'Final Call Sheet',days:1,groups:[]},
  {id:'prelight',stage:'pre',name:'Prelight',nameEN:'Prelight',days:1,groups:[]},
  // ── RODAJE ───────────────────────────────────────────────────────────────────────────────
  {id:'shoot-1',stage:'sht',name:'Rodaje Día 1',nameEN:'Shoot Day 1',days:1,groups:[]},
  {id:'shoot-2',stage:'sht',name:'Rodaje Día 2',nameEN:'Shoot Day 2',days:1,groups:[]},
  {id:'shoot-3',stage:'sht',name:'Rodaje Día 3',nameEN:'Shoot Day 3',days:1,groups:[]},
  {id:'shoot-4',stage:'sht',name:'Rodaje Día 4',nameEN:'Shoot Day 4',days:1,groups:[]},
  // ── VIDEO POST-PRODUCCIÓN ────────────────────────────────────────────────────────────────
  {id:'v-ingest',stage:'vpst',name:'Ingesta y Backup de Medios',nameEN:'Media Ingest & Backup',days:1,groups:['video-post']},
  {id:'v-edit-prep',stage:'vpst',name:'Preparación de Edición',nameEN:'Edit Prep',days:1,groups:['video-post']},
  {id:'v-selects',stage:'vpst',name:'Selección del Editor',nameEN:'Editor\'s Selects',days:1,groups:['video-post']},
  {id:'v-assembly',stage:'vpst',name:'Corte de Ensamble',nameEN:'Assembly Cut',days:1,groups:['video-post']},
  {id:'v-offline',stage:'vpst',name:'Edición Offline',nameEN:'Offline Edit',days:1,groups:['video-post']},
  {id:'v-int-review',stage:'vpst',name:'Revisión Interna de Edición',nameEN:'Internal Edit Review',days:1,groups:['video-post']},
  {id:'v-client-review',stage:'vpst',name:'Revisión de Edición con Cliente',nameEN:'Client Edit Review',days:1,groups:['video-post']},
  {id:'v-rev-r1',stage:'vpst',name:'Ronda 1 de Cambios de Edición',nameEN:'Edit Revision Round 1',days:1,groups:['video-post']},
  {id:'v-rev-r2',stage:'vpst',name:'Ronda 2 de Cambios de Edición',nameEN:'Edit Revision Round 2',days:1,groups:['video-post']},
  {id:'v-pic-lock',stage:'vpst',name:'Picture Lock',nameEN:'Picture Lock',days:1,groups:['video-post']},
  {id:'v-vfx-prep',stage:'vpst',name:'Preparación para VFX',nameEN:'VFX Prep',days:1,groups:['video-post']},
  {id:'v-vfx-review',stage:'vpst',name:'Revisión de VFX',nameEN:'VFX Review',days:1,groups:['video-post']},
  {id:'v-graphics',stage:'vpst',name:'Gráfica',nameEN:'Graphics',days:1,groups:['video-post']},
  {id:'v-conform',stage:'vpst',name:'Conform Online',nameEN:'Online Conform',days:1,groups:['video-post']},
  {id:'v-color',stage:'vpst',name:'Corrección de Color',nameEN:'Color Grade',days:1,groups:['video-post']},
  {id:'v-sound',stage:'vpst',name:'Diseño Sonoro',nameEN:'Sound Design',days:1,groups:['video-post']},
  {id:'v-vo',stage:'vpst',name:'Grabación de VO',nameEN:'VO Record',days:1,groups:['video-post']},
  {id:'v-music',stage:'vpst',name:'Música Final',nameEN:'Music Final',days:1,groups:['video-post']},
  {id:'v-audio-mix',stage:'vpst',name:'Mezcla de Audio',nameEN:'Audio Mix',days:1,groups:['video-post']},
  {id:'v-final-review',stage:'vpst',name:'Revisión Final de Post',nameEN:'Final Post Review',days:1,groups:['video-post']},
  {id:'v-client-final',stage:'vpst',name:'Aprobación Final de Cliente',nameEN:'Client Final Approval',days:1,groups:['video-post']},
  {id:'v-versioning',stage:'vpst',name:'Versionado',nameEN:'Versioning',days:1,groups:['video-post']},
  {id:'v-master-del',stage:'vpst',name:'Entrega de Master',nameEN:'Master Delivery',days:1,groups:['video-post']},
  {id:'v-archive',stage:'vpst',name:'Archivo',nameEN:'Archive',days:1,groups:['video-post']},
  // ── STILL POST-PRODUCCIÓN ────────────────────────────────────────────────────────────────
  {id:'s-ingest',stage:'spst',name:'Ingesta y Backup de Archivos',nameEN:'Media Ingest & Backup',days:1,groups:['still-post']},
  {id:'s-edit-prep',stage:'spst',name:'Preparación de Edición',nameEN:'Edit Prep',days:1,groups:['still-post']},
  {id:'s-first-edit',stage:'spst',name:'Primera Edición',nameEN:'First Edit',days:1,groups:['still-post']},
  {id:'s-gallery',stage:'spst',name:'Galería de Revisión para Cliente',nameEN:'Client Review Gallery',days:1,groups:['still-post']},
  {id:'s-client-sel',stage:'spst',name:'Selección de Cliente',nameEN:'Client Selects',days:1,groups:['still-post']},
  {id:'s-color-clean',stage:'spst',name:'Corrección de Color y Limpieza de Archivos',nameEN:'Color Correction & File Cleanup',days:1,groups:['still-post']},
  {id:'s-retouch',stage:'spst',name:'Retoque',nameEN:'Retouching',days:1,groups:['still-post']},
  {id:'s-int-retouch',stage:'spst',name:'Revisión Interna de Retoque',nameEN:'Internal Retouch Review',days:1,groups:['still-post']},
  {id:'s-client-retouch',stage:'spst',name:'Revisión de Retoque con Cliente',nameEN:'Client Retouch Review',days:1,groups:['still-post']},
  {id:'s-rev-r1',stage:'spst',name:'Ronda 1 de Cambios de Retoque',nameEN:'Retouch Revision Round 1',days:1,groups:['still-post']},
  {id:'s-rev-r2',stage:'spst',name:'Ronda 2 de Cambios de Retoque',nameEN:'Retouch Revision Round 2',days:1,groups:['still-post']},
  {id:'s-final-appr',stage:'spst',name:'Aprobación Final de Selects',nameEN:'Final Selects Approval',days:1,groups:['still-post']},
  {id:'s-output-prep',stage:'spst',name:'Preparación de Entregables Finales',nameEN:'Final Output Prep',days:1,groups:['still-post']},
  {id:'s-versioning',stage:'spst',name:'Versionado / Crops',nameEN:'Versioning / Crops',days:1,groups:['still-post']},
  {id:'s-final-del',stage:'spst',name:'Entrega Final',nameEN:'Final Delivery',days:1,groups:['still-post']},
  {id:'s-archive',stage:'spst',name:'Archivo',nameEN:'Archive',days:1,groups:['still-post']},
]

export const DEFAULT_GROUPS = [
  {key:'casting',    name:'Casting',         nameEN:'Casting'},
  {key:'locations',  name:'Locaciones',      nameEN:'Locations'},
  {key:'wardrobe',   name:'Vestuario',       nameEN:'Wardrobe'},
  {key:'art',        name:'Arte',            nameEN:'Art Department'},
  {key:'boards',     name:'Shooting Boards', nameEN:'Shooting Boards'},
  {key:'video-post', name:'Post Video',      nameEN:'Video Post-Production'},
  {key:'still-post', name:'Post Foto',       nameEN:'Still Post-Production'},
]

export const DEFAULT_CITIES = [
  {name:'Santiago',         lat:-33.4569, lon:-70.6483},
  {name:'New York',         lat:40.7128,  lon:-74.0060},
  {name:'Los Angeles',      lat:34.0522,  lon:-118.2437},
  {name:'Miami',            lat:25.7617,  lon:-80.1918},
  {name:'Bogotá',           lat:4.7110,   lon:-74.0721},
  {name:'Buenos Aires',     lat:-34.6037, lon:-58.3816},
  {name:'Ciudad de México', lat:19.4326,  lon:-99.1332},
  {name:'Madrid',           lat:40.4168,  lon:-3.7038},
  {name:'Barcelona',        lat:41.3874,  lon:2.1686},
]

export const DEFAULT_STAGES = [
  {key:'bid',  name:'Bidding',    nameEN:'Bidding'},
  {key:'pre',  name:'Prepro',     nameEN:'Pre-Production'},
  {key:'sht',  name:'Rodaje',     nameEN:'Shoot'},
  {key:'vpst', name:'Post Video', nameEN:'Video Post-Production'},
  {key:'spst', name:'Post Foto',  nameEN:'Still Post-Production'},
]

export const STAGE_ORDER = {bid:0, pre:1, sht:2, vpst:3, spst:4, pst:5}

export const PALETTE = [
  '#06CCB4','#7CAEFF','#3b82f6','#8b5cf6','#ec4899',
  '#ef4444','#f97316','#f59e0b','#22c55e','#10b981','#0ea5e9',
]
